#cloud-config
datasource:
 OpenStack:
users:
- default:
- name: osa
  lock_passwd: True
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ansiblePubKey}
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
manage_etc_hosts: true
