#cloud-config
datasource:
 OpenStack:
  metadata_urls: ["http://169.254.169.254"]
  max_wait: -1
  timeout: 10
  retries: 5
  apply_network_config: True
package_update: True
packages:
 - bridge-utils
 - iputils
 - lsof
 - lvm2
 - chrony
 - tcpdump
 - python
 - python-devel
 - iperf3
 - qemu-guest-agent
manage_etc_hosts: true
runcmd :
- echo bonding >>/etc/modules-load.d/openstack-ansible.conf
- echo 8021q >>/etc/modules-load.d/openstack-ansible.conf
- systemctl enable chrony
- systemctl start chrony
- echo "kernel.printk='4 1 7 4'">>/etc/sysctl.conf
users:
- default:
- name: osa
  lock_passwd: True
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ansiblePubKey}
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
