#cloud-config
datasource:
 OpenStack:
  apply_network_config: True
users:
- default:
- name: osa
  lock_passwd: True
  shell: /bin/bash
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
write_files:
- content: |
    StrictHostKeyChecking=no
    IdentityFile=~/.ssh/AnsibleKey.pem
  path: /etc/skel/.ssh/config
  permissions: '0600'
- content: | ${hosts}
  path: /etc/cloud/templates/hosts.redhat.tmpl
  append: True
- content: '${ansiblePrivKey}'
  encoding: b64
  path: /etc/skel/.ssh/AnsibleKey.pem
  permissions: '0600'
- content: |
    default via ${gateway} dev ${nic_board}
  path: /etc/sysconfig/network-scripts/route-${nic_board}
  permissions: '0644'
- content: | ${resolv_conf}
  path: /etc/resolv.conf
runcmd :
- systemctl disable --now  firewalld
- systemctl restart network
manage_etc_hosts: true
