locals {
  resolv_conf = "\n    # Generated by cloud-init user-data\n${join("\n",formatlist("    nameserver %s",var.DNSServers))}"
}

data "template_file" "cloud-init-gw" {
  template = file("cloud-init-${var.operatingSystem}-gw.tpl.yml")

  vars = {
    cloud          = var.cloud
    ansiblePrivKey = file("AnsibleKey.pem.b64")
    keyOwner       = "${var.operatingSystem}:${var.operatingSystem}"
    ansiblePubKey  = file("AnsibleKey.pub")
    hosts          = "\n    ${join("    ",
                      data.template_file.hosts_gw.*.rendered)}"
    service_CIDR   = var.service_CIDR
    gateway        = cidrhost(var.service_CIDR,10)
    resolv_conf    = local.resolv_conf
    out_nic        = var.out_nic
  }
}

data "template_file" "cloud-init-worker" {
  template = file("cloud-init-${var.operatingSystem}-worker.tpl.yml")

  vars = {
    cloud          = var.cloud
    ansiblePrivKey = file("AnsibleKey.pem.b64")
    keyOwner       = "${var.operatingSystem}:${var.operatingSystem}"
    ansiblePubKey  = file("AnsibleKey.pub")
    gateway        = cidrhost(var.worker_CIDR,10)
    hosts          = "\n    ${join("    ",
                      data.template_file.hosts_gw.*.rendered,
                      data.template_file.hosts_internal.*.rendered)}"
    resolv_conf    = local.resolv_conf
    worker_nic     = var.worker_nic
  }
}
