#cloud-config
datasource:
 OpenStack:
  metadata_urls: ["http://169.254.169.254"]
  max_wait: -1
  timeout: 10
  retries: 5
  apply_network_config: True
package_update: True
packages:
 - git
 - ntp
 - ntpdate
 - openssh-server
 - sudo
users:
- default:
- name: osa
  lock_passwd: True
  shell: /bin/bash
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
write_files:
- content: |
    StrictHostKeyChecking=no
    IdentityFile=~/.ssh/AnsibleKey.pem
  path: /etc/skel/.ssh/config
  permissions: '0600'
- content: | ${hosts}
  path: /etc/cloud/templates/hosts.redhat.tmpl
  append: True
- content: '${ansiblePrivKey}'
  encoding: b64
  path: /etc/skel/.ssh/AnsibleKey.pem
  permissions: '0600'
runcmd :
- systemctl disable --now  firewalld
manage_etc_hosts: true
