#cloud-config
datasource:
 OpenStack:
  metadata_urls: ["http://169.254.169.254"]
  max_wait: -1
  timeout: 10
  retries: 5
  apply_network_config: True
package_update: True
packages:
 - git
 - ntp
 - ntpdate
 - openssh-server
 - python
 - sudo
 - ansible
 - nload
 - bmon
 - netperf
users:
- default:
- name: lamp
  lock_passwd: True
  shell: /bin/bash
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
write_files:
- content: |
    StrictHostKeyChecking=no
    IdentityFile=~/.ssh/AnsibleKey.pem
  path: /etc/skel/.ssh/config
  permissions: '0600'
- content: | ${info}
    Built from ${buildType} image ${imageRef}
    Running on ${cloud}
  path: /opt/terraform/cloudinfo.txt
  permissions: '0644'
- content: | ${hosts}
  path: /etc/cloud/templates/hosts.tmpl
  permissions: '0644'
- content: '${ansiblePrivKey}'
  encoding: b64
  path: /etc/skel/.ssh/AnsibleKey.pem
  permissions: '0600'
runcmd :
- cat /etc/cloud/templates/hosts.tmpl >> /etc/hosts
- cat /etc/cloud/templates/hosts.tmpl >> /etc/cloud/templates/hosts.redhat.tmpl
- yum install git ntp ntpdate openssh-server python-devel sudo '@Developement Tools'
- systemctl stop firewalld
- systemctl mask firewalld
manage_etc_hosts: true
