#cloud-config
datasource:
 OpenStack:
  metadata_urls: ["http://169.254.169.254"]
  max_wait: -1
  timeout: 10
  retries: 5
  apply_network_config: True
package_update: True
packages:
 - bridge-utils
 - iputils
 - lsof
 - lvm2
 - chrony
 - tcpdump
 - python
 - python-devel
 - iperf3
 - nload
 - bmon
 - netperf
manage_etc_hosts: true
users:
- default:
- name: lamp
  lock_passwd: True
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ansiblePubKey}
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
