#cloud-config
write_files:
- content: |
    StrictHostKeyChecking=no
    IdentityFile=~/.ssh/AnsibleKey.pem
  path: /etc/skel/.ssh/config
  permissions: '0600'
- content: | ${info}
    Built from ${buildType} image ${imageRef}
    Running on ${cloud}
  path: /opt/terraform/cloudinfo.txt
  permissions: '0644'
- content: | ${hosts}
  path: /etc/cloud/templates/hosts.tmpl
  permissions: '0644'
- content: '${ansiblePrivKey}'
  encoding: b64
  path: /etc/skel/.ssh/AnsibleKey.pem
  permissions: '0600'
runcmd :
- cat /etc/cloud/templates/hosts.tmpl >> /etc/hosts
- cat /etc/cloud/templates/hosts.tmpl >> /etc/cloud/templates/hosts.debian.tmpl
manage_etc_hosts: true
users:
- default:
- name: osa
  lock_passwd: True
  shell: /bin/bash
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
package_update: True
packages:
 - git
 - ansible
 - python
 - python-dev
 - build-essential
 - ntpdate
 - ntp
 - iperf3
 - qemu-guest-agent
 - watchdog
