#cloud-config
datasource:
 OpenStack:
manage_etc_hosts: true
users:
- default:
- name: lamp
  lock_passwd: True
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ansiblePubKey}
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
package_update: True
packages:
 - bridge-utils
 - lsof
 - tcpdump
 - python
 - iperf3
 - nload
 - bmon
 - netperf
